
package com.mycompany.exemplo.swing;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author diego
 */

//Para alterar algo utilize sempre o padrão "SET"
//Para recuperar o valor de algo utilize o padrão "GET"

//Lembre de sempre alterar o nome dos componentes(variable name)

public class TesteSwing extends javax.swing.JFrame {

    Random random = new Random();
    
    /**
     * Creates new form TesteSwing
     */
    
    //Tudo o que for escrito aqui dentro será realizado no ato de construção do
    //programa.
    
    public TesteSwing() {
        initComponents();
        
        //Podemos configurar o valor máximo da barra
        prgDados.setMaximum(100);
        
        //Podemos configurar o valor mínimo da barra
        prgDados.setMinimum(0);
        
        //Atribuindo um valor randômico toda vez que iniciamos o programa.
        prgDados.setValue(random.nextInt(101));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto1 = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        btnAcao = new javax.swing.JToggleButton();
        lblResultado = new javax.swing.JLabel();
        lblLigado = new javax.swing.JLabel();
        rdbLiga = new javax.swing.JRadioButton();
        prgDados = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTexto1.setText("Testando");

        btnClick.setText("Click me");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnAcao.setText("Trocar valor");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        lblResultado.setText("--------------------------------------------------------");

        lblLigado.setText("Está desligado.");

        rdbLiga.setText("Ligar/Desligar");
        rdbLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLigaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAcao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClick, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdbLiga)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLigado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(prgDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClick)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado))
                .addGap(18, 18, 18)
                .addComponent(btnAcao)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLigado)
                    .addComponent(prgDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbLiga)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        
        //Criando variável com o valor antigo(atual no label).
        String valorAntigo = lblTexto1.getText();
        
        //Concatenando valor antigo + 123.
        lblTexto1.setText(valorAntigo + " 123");
        
        //Alterando cores de um texto
        
        //Podemos utilizar a classe "Color" passando o nome da cor como no exemplo
        //abaixo(confira as cores existentes).
        lblTexto1.setForeground(Color.red);
        
        //Ou posso utilizar o método .decode passando uma cor no padrão Hexadecimal.
        //Exemplo:
        //lblTexto1.setForeground(Color.decode("#8e44ad"));
        
    }//GEN-LAST:event_btnClickActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        
        //Criando variável e atribuindo o texto digitado pelo usuário no TextField.
        String textoUsuario = txtUsuario.getText();
        
        //Atribuindo o valor contido na variável para a label.
        lblResultado.setText(textoUsuario);
        
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void rdbLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLigaActionPerformed

        //Caso queira criar variáveis do tipo booleano utilize a classe Boolean.
        //Exemplo:
        //Boolean teste = true;
        
        //O método .isSelected() do radio button retorna um booleano
        //Nesse caso se o valor for "true" entra no "if" caso contrário entrará no "else"
        //Modificando o texto de acordo.
        if (rdbLiga.isSelected()) {
            lblLigado.setText("Está ligado!");
        }else{
            lblLigado.setText("Está desligado!");
        }
        
    }//GEN-LAST:event_rdbLigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAcao;
    private javax.swing.JButton btnClick;
    private javax.swing.JLabel lblLigado;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JProgressBar prgDados;
    private javax.swing.JRadioButton rdbLiga;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
